<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = Product::insert([
            [
                'name' => 'Xpander Active', 
                'jenis_id' => 2,
                'merks_id' => 4,
                'slug' => 'mitsubishi-xpander-active-mpv',
                'image' => 'images/products/mitsubishi-xpander-active-mpv.jpg', //INI
                'price' => 310000000,
                'location' => 'Gorontalo',
                'description' => json_encode([
                    'top_speed' => '175',
                    'engine' => '1.5L Turbo',
                    'power' => '105',
                    'power_unit' => 'hp',
                    'transmission' => 'cvt',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.1',
                    'seat_capacity' => '7',
                    'width' => '1750',
                    'length' => '4475',
                    'height' => '1695',
                    'ground_clearance' => '205',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Camry', 
                'jenis_id' => 1,
                'merks_id' => 1,
                'slug' => 'toyota-camry-sedan',
                'image' => 'images/products/toyota-camry-sedan.jpg', //INI
                'price' => 820000000,
                'location' => 'Jakarta',
                'description' => json_encode([
                    'top_speed' => '210',
                    'engine' => '2.5L I4',
                    'power' => '203',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.8',
                    'seat_capacity' => '5',
                    'width' => '1840',
                    'length' => '4885',
                    'height' => '1445',
                    'ground_clearance' => '145',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Elevate', 
                'jenis_id' => 3,
                'merks_id' => 3,
                'slug' => 'honda-elevate-suv',
                'image' => 'images/products/honda-elevate-suv.jpg', //INI
                'price' => 360000000,
                'location' => 'Lampung',
                'description' => json_encode([
                    'top_speed' => '190',
                    'engine' => '1.5L I4',
                    'power' => '121',
                    'power_unit' => 'hp',
                    'transmission' => 'cvt',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.0',
                    'seat_capacity' => '5',
                    'width' => '1790',
                    'length' => '4312',
                    'height' => '1650',
                    'ground_clearance' => '220',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Ertiga Max', 
                'jenis_id' => 2,
                'merks_id' => 5,
                'slug' => 'suzuki-ertiga-max-mpv',
                'image' => 'images/products/suzuki-ertiga-max-mpv.jpg', //INI
                'price' => 210000000,
                'location' => 'Bali',
                'description' => json_encode([
                    'top_speed' => '175',
                    'engine' => '1.5L I4',
                    'power' => '105',
                    'power_unit' => 'hp',
                    'transmission' => 'manual',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.1',
                    'seat_capacity' => '7',
                    'width' => '1735',
                    'length' => '4395',
                    'height' => '1690',
                    'ground_clearance' => '185',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Kona X', 
                'jenis_id' => 4,
                'merks_id' => 6,
                'slug' => 'hyundai-kona-x-crossover',
                'image' => 'images/products/hyundai-kona-x-crossover.jpg', //INI
                'price' => 440000000,
                'location' => 'Aceh',
                'description' => json_encode([
                    'top_speed' => '210',
                    'engine' => '2.0L I4',
                    'power' => '147',
                    'power_unit' => 'hp',
                    'transmission' => 'dct',
                    'fuel_type' => 'hybrid',
                    'fuel_consumption' => '5.3',
                    'seat_capacity' => '5',
                    'width' => '1800',
                    'length' => '4205',
                    'height' => '1565',
                    'ground_clearance' => '170',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Carnival LX', 
                'jenis_id' => 5,
                'merks_id' => 8,
                'slug' => 'kia-carnival-lx-minivans',
                'image' => 'images/products/kia-carnival-lx-minivans.jpg', //INI
                'price' => 690000000,
                'location' => 'Yogyakarta',
                'description' => json_encode([
                    'top_speed' => '200',
                    'engine' => '3.5L V6',
                    'power' => '290',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '9.5',
                    'seat_capacity' => '8',
                    'width' => '1995',
                    'length' => '5155',
                    'height' => '1740',
                    'ground_clearance' => '180',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Triton Sport', 
                'jenis_id' => 6,
                'merks_id' => 4,
                'slug' => 'mitsubishi-triton-sport-pickup-truck',
                'image' => 'images/products/mitsubishi-triton-sport-pickup-truck.jpg', //INI
                'price' => 385000000,
                'location' => 'Bandung',
                'description' => json_encode([
                    'top_speed' => '185',
                    'engine' => '2.4L Diesel',
                    'power' => '178',
                    'power_unit' => 'hp',
                    'transmission' => 'manual',
                    'fuel_type' => 'solar',
                    'fuel_consumption' => '7.5',
                    'seat_capacity' => '5',
                    'width' => '1815',
                    'length' => '5300',
                    'height' => '1780',
                    'ground_clearance' => '220',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => '430i M-Sport', 
                'jenis_id' => 7,
                'merks_id' => 9,
                'slug' => 'bmw-430i-m-sport-coupe',
                'image' => 'images/products/bmw-430i-m-sport-coupe.jpg', //INI
                'price' => 1250000000,
                'location' => 'Solo',
                'description' => json_encode([
                    'top_speed' => '250',
                    'engine' => '2.0L Turbo I4',
                    'power' => '255',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.4',
                    'seat_capacity' => '4',
                    'width' => '1852',
                    'length' => '4783',
                    'height' => '1395',
                    'ground_clearance' => '130',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Mazda6 Touring', 
                'jenis_id' => 10,
                'merks_id' => 10,
                'slug' => 'mazda-mazda6-touring-wagon',
                'image' => 'images/products/mazda-mazda6-touring-wagon.jpg', //INI
                'price' => 415000000,
                'location' => 'Malang',
                'description' => json_encode([
                    'top_speed' => '215',
                    'engine' => '2.5L I4',
                    'power' => '187',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.2',
                    'seat_capacity' => '5',
                    'width' => '1840',
                    'length' => '4800',
                    'height' => '1480',
                    'ground_clearance' => '165',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Gran Max Urban', 
                'jenis_id' => 8,
                'merks_id' => 2,
                'slug' => 'daihatsu-gran-max-urban-van',
                'image' => 'images/products/daihatsu-gran-max-urban-van.jpg', //INI
                'price' => 135000000,
                'location' => 'Lombok',
                'description' => json_encode([
                    'top_speed' => '160',
                    'engine' => '1.3L I4',
                    'power' => '87',
                    'power_unit' => 'hp',
                    'transmission' => 'manual',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '8.0',
                    'seat_capacity' => '8',
                    'width' => '1665',
                    'length' => '4195',
                    'height' => '1900',
                    'ground_clearance' => '180',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Almaz Neo', 
                'jenis_id' => 3,
                'merks_id' => 7,
                'slug' => 'wuling-almaz-neo-suv',
                'image' => 'images/products/wuling-almaz-neo-suv.jpg', //INI
                'price' => 370000000,
                'location' => 'Palembang',
                'description' => json_encode([
                    'top_speed' => '190',
                    'engine' => '1.5L Turbo',
                    'power' => '140',
                    'power_unit' => 'hp',
                    'transmission' => 'cvt',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.0',
                    'seat_capacity' => '7',
                    'width' => '1850',
                    'length' => '4655',
                    'height' => '1760',
                    'ground_clearance' => '200',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Seal Premium', 
                'jenis_id' => 1,
                'merks_id' => 17,
                'slug' => 'byd-seal-premium-sedan',
                'image' => 'images/products/byd-seal-premium-sedan.jpg', //INI
                'price' => 629000000,
                'location' => 'Kendari',
                'description' => json_encode([
                    'top_speed' => '180',
                    'engine' => 'Electric Dual Motor',
                    'power' => '230',
                    'power_unit' => 'kw',
                    'transmission' => 'automatic',
                    'fuel_type' => 'listrik',
                    'fuel_consumption' => '0.0',
                    'seat_capacity' => '5',
                    'width' => '1875',
                    'length' => '4800',
                    'height' => '1460',
                    'ground_clearance' => '145',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'D-Max Z Edition', 
                'jenis_id' => 6,
                'merks_id' => 11,
                'slug' => 'isuzu-d-max-z-edition-pickup-truck',
                'image' => 'images/products/isuzu-d-max-z-edition-pickup-truck.jpg', //INI
                'price' => 485000000,
                'location' => 'Makasar',
                'description' => json_encode([
                    'top_speed' => '180',
                    'engine' => '3.0L Diesel',
                    'power' => '190',
                    'power_unit' => 'hp',
                    'transmission' => 'manual',
                    'fuel_type' => 'solar',
                    'fuel_consumption' => '7.8',
                    'seat_capacity' => '5',
                    'width' => '1870',
                    'length' => '5295',
                    'height' => '1800',
                    'ground_clearance' => '235',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Everest Trail', 
                'jenis_id' => 3,
                'merks_id' => 12,
                'slug' => 'ford-everest-trail-suv',
                'image' => 'images/products/ford-everest-trail-suv.jpg', //INI
                'price' => 775000000,
                'location' => 'Maksar',
                'description' => json_encode([
                    'top_speed' => '210',
                    'engine' => '2.0L Bi-Turbo',
                    'power' => '210',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'solar',
                    'fuel_consumption' => '8.2',
                    'seat_capacity' => '7',
                    'width' => '1860',
                    'length' => '4914',
                    'height' => '1837',
                    'ground_clearance' => '227',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'Corolla Cross', 
                'jenis_id' => 4,
                'merks_id' => 1,
                'slug' => 'toyota-corolla-cross-crossover',
                'image' => 'images/products/toyota-corolla-cross-crossover.jpg', //INI
                'price' => 410000000,
                'location' => 'Pontianak',
                'description' => json_encode([
                    'top_speed' => '190',
                    'engine' => '1.8L Hybrid',
                    'power' => '138',
                    'power_unit' => 'hp',
                    'transmission' => 'cvt',
                    'fuel_type' => 'hybrid',
                    'fuel_consumption' => '4.5',
                    'seat_capacity' => '5',
                    'width' => '1825',
                    'length' => '4460',
                    'height' => '1620',
                    'ground_clearance' => '185',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Model S Plaid', 
                'jenis_id' => 1,
                'merks_id' => 13,
                'slug' => 'tesla-model-s-plaid-sedan',
                'image' => 'images/products/tesla-model-s-plaid-sedan.jpg', //INI
                'price' => 1890000000,
                'location' => 'Jayapura',
                'description' => json_encode([
                    'top_speed' => '322',
                    'engine' => 'Electric Tri-Motor',
                    'power' => '1020',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'listrik',
                    'fuel_consumption' => '0.0',
                    'seat_capacity' => '5',
                    'width' => '1963',
                    'length' => '4970',
                    'height' => '1445',
                    'ground_clearance' => '140',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'C-Class Cabriolet', 
                'jenis_id' => 11,
                'merks_id' => 14,
                'slug' => 'mercedes-benz-c-class-cabriolet-convertible',
                'image' => 'images/products/mercedes-benz-c-class-cabriolet-convertible.jpg', //INI
                'price' => 925000000,
                'location' => 'Palopo',
                'description' => json_encode([
                    'top_speed' => '250',
                    'engine' => '2.0L Turbocharged I4',
                    'power' => '150',
                    'power_unit' => 'kw',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.4',
                    'seat_capacity' => '5',
                    'width' => '1810',
                    'length' => '4696',
                    'height' => '1409',
                    'ground_clearance' => '130',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Civic Liftback', 
                'jenis_id' => 10,
                'merks_id' => 3,
                'slug' => 'honda-civic-liftback-sportback',
                'image' => 'images/products/honda-civic-liftback-sportback.jpg', //INI
                'price' => 280000000,
                'location' => 'Semarang',
                'description' => json_encode([
                    'top_speed' => '220',
                    'engine' => '1.5L Turbo I4',
                    'power' => '173',
                    'power_unit' => 'hp',
                    'transmission' => 'cvt',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.6',
                    'seat_capacity' => '5',
                    'width' => '1799',
                    'length' => '4658',
                    'height' => '1416',
                    'ground_clearance' => '135',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'i30 Tourer', 
                'jenis_id' => 9,
                'merks_id' => 6,
                'slug' => 'hyundai-i30-tourer-wagon',
                'image' => 'images/products/hyundai-i30-tourer-wagon.jpg', //INI
                'price' => 250000000,
                'location' => 'Serang',
                'description' => json_encode([
                    'top_speed' => '200',
                    'engine' => '1.6L I4',
                    'power' => '136',
                    'power_unit' => 'hp',
                    'transmission' => 'dct',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.9',
                    'seat_capacity' => '5',
                    'width' => '1795',
                    'length' => '4585',
                    'height' => '1465',
                    'ground_clearance' => '140',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Megane E-Tech', 
                'jenis_id' => 3,
                'merks_id' => 15,
                'slug' => 'renault-megane-e-tech-suv',
                'image' => 'images/products/renault-megane-e-tech-suv.jpg', //INI
                'price' => 510000000,
                'location' => 'Parepare',
                'description' => json_encode([
                    'top_speed' => '160',
                    'engine' => 'Electric Motor',
                    'power' => '160',
                    'power_unit' => 'kw',
                    'transmission' => 'automatic',
                    'fuel_type' => 'listrik',
                    'fuel_consumption' => '0.0',
                    'seat_capacity' => '5',
                    'width' => '1810',
                    'length' => '4200',
                    'height' => '1500',
                    'ground_clearance' => '150',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Mazda3 Prime', 
                'jenis_id' => 1,
                'merks_id' => 10,
                'slug' => 'mazda-mazda3-prime-sedan',
                'image' => 'images/products/mazda-mazda3-prime-sedan.jpg', //INI
                'price' => 325000000,
                'location' => 'Medan',
                'description' => json_encode([
                    'top_speed' => '210',
                    'engine' => '2.0L I4',
                    'power' => '155',
                    'power_unit' => 'hp',
                    'transmission' => 'automatic',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.5',
                    'seat_capacity' => '5',
                    'width' => '1795',
                    'length' => '4660',
                    'height' => '1440',
                    'ground_clearance' => '145',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'SX4 S-Cross', 
                'jenis_id' => 4,
                'merks_id' => 5,
                'slug' => 'suzuki-sx4-s-cross-crossover',
                'image' => 'images/products/suzuki-sx4-s-cross-crossover.jpg', //INI
                'price' => 210000000,
                'location' => 'Binjai',
                'description' => json_encode([
                    'top_speed' => '185',
                    'engine' => '1.4L Turbo',
                    'power' => '140',
                    'power_unit' => 'hp',
                    'transmission' => 'manual',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '6.7',
                    'seat_capacity' => '5',
                    'width' => '1785',
                    'length' => '4300',
                    'height' => '1595',
                    'ground_clearance' => '180',
                ]),
                'condition' => 'bekas',
                'is_active' => true,
            ],
            [
                'name' => 'Koup Turbo', 
                'jenis_id' => 7,
                'merks_id' => 8,
                'slug' => 'kia-koup-turbo-coupe',
                'image' => 'images/products/kia-koup-turbo-coupe.jpg', //INI
                'price' => 470000000,
                'location' => 'Salatiga',
                'description' => json_encode([
                    'top_speed' => '225',
                    'engine' => '1.6L Turbo',
                    'power' => '201',
                    'power_unit' => 'hp',
                    'transmission' => 'dct',
                    'fuel_type' => 'bensin',
                    'fuel_consumption' => '7.8',
                    'seat_capacity' => '4',
                    'width' => '1780',
                    'length' => '4480',
                    'height' => '1420',
                    'ground_clearance' => '135',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => '208 e-GT', 
                'jenis_id' => 12,
                'merks_id' => 18,
                'slug' => 'peugeot-208-e-gt-hatchback',
                'image' => 'images/products/peugeot-208-e-gt-hatchback.jpg', //INI
                'price' => 515000000,
                'location' => 'Langsa',
                'description' => json_encode([
                    'top_speed' => '150',
                    'engine' => 'Electric Motor',
                    'power' => '100',
                    'power_unit' => 'kw',
                    'transmission' => 'automatic',
                    'fuel_type' => 'listrik',
                    'fuel_consumption' => '0.0',
                    'seat_capacity' => '5',
                    'width' => '1745',
                    'length' => '4055',
                    'height' => '1430',
                    'ground_clearance' => '140',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
            [
                'name' => 'XC40 Recharge', 
                'jenis_id' => 3,
                'merks_id' => 16,
                'slug' => 'volvo-xc40-recharge-suv',
                'image' => 'images/products/volvo-xc40-recharge-suv.jpg', //INI
                'price' => 1280000000,
                'location' => 'Banjarbaru',
                'description' => json_encode([
                    'top_speed' => '180',
                    'engine' => 'Electric Dual Motor',
                    'power' => '300',
                    'power_unit' => 'kw',
                    'transmission' => 'automatic',
                    'fuel_type' => 'listrik',
                    'fuel_consumption' => '0.0',
                    'seat_capacity' => '5',
                    'width' => '1863',
                    'length' => '4440',
                    'height' => '1652',
                    'ground_clearance' => '175',
                ]),
                'condition' => 'baru',
                'is_active' => true,
            ],
        ]);
    }
}
